<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0KDP1L5" name="Default test" tests="9" failures="1" timestamp="28 Sep 2017 04:11:19 GMT" time="3.447" errors="0">
  <testcase name="testAddBooks" time="2.286" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testAddBooks" time="0.125" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testAddBooks" time="0.125" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testAddBooks" time="0.125" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testAddBooks" time="0.125" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testAddBooks" time="0.11" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testExcetption" time="0.031" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testGetListOfBooks" time="0.125" classname="com.scp.hinernateCrudOperations.TestBookImpl"/>
  <testcase name="testUpdate" time="0.364" classname="com.scp.hinernateCrudOperations.TestBookImpl">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;...1&amp;gt; but was:&amp;lt;...&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...1> but was:<...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at com.scp.hinernateCrudOperations.TestBookImpl.testUpdate(TestBookImpl.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- testUpdate -->
</testsuite> <!-- Default test -->
